steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/dockers'
  args: ['build', '-t', 'gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA', '.']

# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA']

Step 3: Deploy the Docker container to Google Kubernetes Engine (GKE)
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/chat_bot7'
  - 'your-container-name=gcr.io/lumen-b-ctl-047/chat_bo1t$SHORT_SHA'
  - '--namespace=default'

images:
- 'gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA'

# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   script: |
#     gcloud run deploy cloudrunservice --image us-docker.pkg.dev/cloudrun/container/chat_bot --region us-central1 --platform managed --allow-unauthenticated
