steps:
- name: 'gcr.io/cloud-builders/gcloud'
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Replace with your actual zone
    - 'CLOUDSDK_CONTAINER_CLUSTER=chatbot'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud config set project lumen-b-ctl-047

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/chat_bot7'
    - 'chat_bot1=gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA'
    - '--namespace=default'

images:
- 'gcr.io/lumen-b-ctl-047/chat_bot1:$SHORT_SHA'
